#!/bin/sh

#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=16:mem=8gb
#PBS -J 1-3

MYJOBID=$(echo ${PBS_ARRAY_INDEX}| sed 's/\[.*//')
params=$(sed -n ${PBS_ARRAY_INDEX}p /Users/paul/Repositories/generate-pbs/test.csv)

mkdir -p $MYJOBID
destDir=$(pwd)/$MYJOBID

cp $HOME/Repositories/Repositories $TMPDIR -r
cd $TMPDIR/Repositories

module load matlab
matlab -nodesktop -nojvm -r 'maxNumCompThreads(16); main('$params', "24:00:00"); quit'

mv data-* $destDir
